name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '/home/runner/work/codemirror/codemirror/node_modules'
          key: ${{ runner.os }}-modules

      - run: npm install

      - run: npm test
